name: Gen doc

on: [push]

jobs:

  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Generate doc
      run: |
        # Start the godoc server in the background
        godoc -http=localhost:6060 &

        # Retrieve the index.html for the package
        wget http://localhost:6060/pkg/github.com/Spartan0nix/zabbix-go-sdk/ > docs/index.html

        # Kill the godoc server
        godoc_pid=$(ps -C godoc | awk '{ print $1 }' | sed 's/PID//g;/^$/d')
        kill -9 $godoc_pid
